spring.application.name=maintain-it
spring.datasource.url=jdbc:mysql://localhost:3306/maintain_it
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true